filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.name: "openresty-nginx"
          config:
            - type: docker
              containers.stream: all
              containers.ids:
                - ${data.docker.container.id}

output.logstash:
  hosts: ["logstash:5043"]

setup:
  kibana:
    host: "kibana:5601"

  template.name: "filebeat"
  template.pattern: "filebeat-*"