version: "3.6"
services:
  nginx:
    image: openresty/openresty:jessie
    container_name: openresty-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx.conf.d/:/usr/local/openresty/nginx/conf/conf.d/
      - ./lua:/usr/local/openresty/nginx/lua
      - logs-volume:/var/log/nginx

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: logstash
    ports:
      - "5043:5043"
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      # - ./logstash/config/:/usr/share/logstash/config/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch

  filebeat:
    # image: docker.elastic.co/beats/filebeat:6.2.4
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    container_name: filebeat
    volumes:
    #   - logs-volume:/var/log/nginx
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx
      - elasticsearch
      - kibana
    links:
      - elasticsearch
      - kibana

volumes:
  logs-volume:
    name: logs-volume