FROM openresty/openresty:jessie
RUN luarocks install luajson

# RUN mkdir /var/log/nginx

# RUN touch /var/log/nginx/request-response.log && \
#     chmod 777 /var/log/nginx/request-response.log

# RUN ln -sf /dev/stdout /var/log/nginx/request-response.log